seed: 42
epochs: 50
img_size: 384
model_name: efficientnet_b0_ns
train_batch_size: 32
valid_batch_size: 64
learning_rate: 1e-4
scheduler: 'CosineAnnealingLR'
min_lr: 1e-6
T_max: 500
weight_decay: 1e-6
fold : 0
n_fold: 5
n_accumulate: 1