data:
  shape: [3, 32, 32] # shape of the input data (channel, height, width)
  classes:
    0: 'airplane'
    1: 'automobile'
    2: 'bird'
    3: 'cat'
    4: 'deer'
    5: 'dog'
    6: 'frog'
    7: 'horse'
    8: 'ship'
    9: 'truck'

train:
  batch_size: 64
  lr : 0.01
  momentum: 0.5
  epochs: 20
  val_split: 0